spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///G:/microservices/git-localconfig-repo
          default-label: master
server:
  port: 8888
